### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by magiccDev** [corbosman/nginx-php#1]
Getting this error.

413 Request Entity Too Large
 
Could we add this to env ?

Looking forward to hearing from you

**Comment by corbosman** [comment]
Is this client_max_body_size?  One option would be to just provide your own default.conf and mount it on /etc/nginx/conf.d/default.conf.  Not really scalable for me to allow for environment options for all these nginx directives. This way you can modify your nginx config whatever way you like.   You can see my default.conf in the github repo, just copy it, and modify it whichever way you like. 

```
docker run -v ~/Code/myapp:/app -v default.conf:/etc/nginx/conf.d/default.conf corbosman/nginx-php:7.3 php artisan
```

**Comment by magiccDev** [comment]
Thank you for your quick reply. 

I was using your script for a long time, this issue recently started when I am uploading a profile picture. (POST Request)

https://github.com/corbosman/nginx-php/blob/1886f5bf945cc41fe795268f25c458a848966cc2/nginx/default.conf#L10

As you see here, you have already added 128M, I also using the same config :(

**Comment by magiccDev** [comment]
echo "client_max_body_size 10G;" > uploadsize.conf
docker cp uploadsize.conf <container>:/etc/nginx/conf.d/uploadsize.conf
docker restart <container>

--------------------

Worked with the settings above
