### ISSUE TITLE
why php with nginx not use unix.sock in www.conf

### ISSUE THREAD

**Issue by jlwgeneral** [corbosman/nginx-php#2]
^

**Comment by jlwgeneral** [comment]
and dont know how start stop restart nginx or php-fpm

**Comment by corbosman** [comment]
I don't think it really matters that much if you use a file socket or a network socket. But feel free to do some performance testing.  What i've read is that network sockets have less issues on some platforms like windows.  

To start/stop nginx you just restart the image.  That's true for pretty much all docker images, it's how docker was designed.

**Comment by jlwgeneral** [comment]
i dont agreen, n we usually use sock, because it has better performance, I have changed some things based on you, and added supervisor，thanks

**Comment by corbosman** [comment]
I just did a small benchmark with both network sockets and file sockets. Granted, this is not a really exhaustive test, but it shows how little this setting matters when it's all in 1 container. I used ApacheBench. 

First file sockets

```
Time taken for tests:   6.082 seconds
Complete requests:      1000
Total transferred:      81917884 bytes
HTML transferred:       81754884 bytes
Requests per second:    164.42 [#/sec] (mean)
Time per request:       12.164 [ms] (mean)
Time per request:       6.082 [ms] (mean, across all concurrent requests)
Transfer rate:          13153.32 [Kbytes/sec] received
```

Then network sockets

```
Concurrency Level:      2
Time taken for tests:   6.094 seconds
Complete requests:      1000
Total transferred:      81916778 bytes
HTML transferred:       81753778 bytes
Requests per second:    164.09 [#/sec] (mean)
Time per request:       12.189 [ms] (mean)
Time per request:       6.094 [ms] (mean, across all concurrent requests)
Transfer rate:          13126.33 [Kbytes/sec] received
```

I did several runs, and the results were similar every time. Maybe if you really tweak this you can get slightly better results, but I dont think it significantly matters.
